### ISSUE TITLE
Add CI to Mirror

### ISSUE THREAD

**Issue by jonasabreu** [vidageek/mirror#13]
install or write a simple CI runner

**Comment by adrianoalmeida7** [comment]
in order to put it on CI's , we may provide a script which get the tubaina dependency and somehow ensure it's already on the machine

**Comment by jonasabreu** [comment]
i guess it will be easier to just clone tubaina repo, and run mvn install on tubaina e tubaina plugin.

**Comment by adrianoalmeida7** [comment]
I just got a barrier to finish this task. Mirror also depends on tubaina-maven-plugin, and it's pom is outdated (it points to 1.2 SNAPSHOT, when it should point to 1.6 SNAPSHOT). I can't smoothly do an mvn install on it. Maybe I can do a cheat, but it would be better if they change their trunk to point to the real version.

**Comment by jonasabreu** [comment]
I'm taking a look at this, since I'm commiter from tubaina and developed the maven plugin. I'll try to add the project to maven repo, so this problem will disapear.

**Comment by garcia-jj** [comment]
Travis issue already solved this issue, right?

**Comment by jonasabreu** [comment]
yes. Thanks for noticing.
