### ISSUE TITLE
Extract method and constructor parameter names

### ISSUE THREAD

**Issue by jonasabreu** [vidageek/mirror#3]
I want to be able to use Mirror as a facade over paranamer.

**Comment by adrianoalmeida7** [comment]
may use jarjar to embed paranamer under the project.
in order to use paranamer, the user will need to compile on debug mode. The default behavior is to be compiled under debug mode. If it's not on debug mode, should raise an explanatory exception regarding the correct provider to use.

**Comment by jonasabreu** [comment]
Duplicate of #15
