### ISSUE TITLE
Constructor for class net.vidageek.mirror.dsl.Mirror is too slow

### ISSUE THREAD

**Issue by rafaeldff** [vidageek/mirror#32]
Running a profiler over http://github.com/rafaeldff/Iogi revealed that calls to the primary constructor in class net.vidageek.mirror.dsl.Mirror are a hotspot. A brief glance shows that it might be doing some IO, which isn't very desirable in tight loops.

(A workaround in Iogi was to extract the Mirror instance to a static constant. I hope no memory leaks come about because of this).

**Comment by jonasabreu** [comment]
This is something I was worried about. We'll implement some kind of caching so Mirror will read the configuration only once.

**Comment by jonasabreu** [comment]
commit 2e87bac0d5d1924eb16a8cbffe39c8d6949b683d fix this.

**Comment by rafaeldff** [comment]
Very cool, but maybe it would be a good idea to use a weak reference to avoid any possibility of a leak.
