### ISSUE TITLE
Proxifier similar to the one in VRaptor

### ISSUE THREAD

**Issue by rafaeldff** [vidageek/mirror#33]
Helps to create proxies for concrete classes. Using CGLIB, in can pass default arguments to the class constructor, or it can use some objenesis black magic to instantiate without calling a constructor.

In VRaptor:
br.com.caelum.vraptor.proxy.DefaultProxifier

**Comment by jonasabreu** [comment]
commit 602e77dede87e1b0c60142f6d9d208e1ae734b41 fix this.
