### ISSUE TITLE
Convenience Method for Defining/Choosing A Method

### ISSUE THREAD

**Issue by nelz9999** [vidageek/mirror#44]
Instead of requiring the client to submit the list of parameter classes to uniquely identify a method, provide a convenient way to grab the uniquely named method without having to define the parameters.

Example:
MyTestClass {
 void myUniquelyNamedMethod(String, Long, Integer){}
}

Currently, this would require something like this:
Method m = new Mirror().on(MyTestClass.class).reflect().method("myUniquelyNamedMethod").withArgs(String.class, Long.class, Integer.class);

My suggestion would be a method that looks something like this, but still returns the same method as the above expression:
Method m = new Mirror().on(MyTestClass.class).reflect().method("myUniquelyNamedMethod").withUniqueMethodName();

**Comment by jonasabreu** [comment]
Hi nelz9999,

I'm adding this to our 1.6 release. The last method will be something like withAnyArgs() and will throw an MirrorException if there is more than one method.

Thanks!

**Comment by jonasabreu** [comment]
commit b3295f821bf7a1d8ede2a9f9c3eb294324a258fb fix this.
