### ISSUE TITLE
license clarity

### ISSUE THREAD

**Issue by jeremycarroll** [vidageek/mirror#52]
I am considering downloading and using mirror but cannot see the license terms easily on your web site, and the license is not obvious in the sources. Suggest a clear link on main web page that says "license" and also a license file near the top of the repo

**Comment by jonasabreu** [comment]
Hi,

Sorry for taking this long. The license is Apache 2.0. 

And I'll fix this problem asap.

**Comment by jonasabreu** [comment]
Hi,

commit 13fc00387f5bfe7bd0815726ccfe114ae6317821 fix this problem.
