### ISSUE TITLE
Configure Travis to check if tests are fail

### ISSUE THREAD

**Issue by garcia-jj** [vidageek/mirror#73]
We can see on each pull request if everything is fine.

**Comment by jonasabreu** [comment]
This would be really cool!

**Comment by garcia-jj** [comment]
I don't remember how to do. But as you are the project owner you need to configure in the hooks section in project admin. After, you must put a `.travis` file with the content `language: java`.

**Comment by jonasabreu** [comment]
Travis is really simpler than it was the last time I tried it. ad821cf49c847baaf97b551a6441564752f1514e closes this issue.
